
services:
  postgres:
    image: timescale/timescaledb-ha:pg18
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    shm_size: 128mb
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-example}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../data/backups:/backups

volumes:
  postgres-data:
    driver: local
