# [target.aarch64-unknown-linux-gnu]
# linker = "/usr/bin/aarch64-linux-gnu-gcc"

[test]
jobs = 4

[profile.test]
debug = 0          # or 1 if you still want line numbers
split-debuginfo = "packed"
strip = true
