# [target.aarch64-unknown-linux-gnu]
# linker = "/usr/bin/aarch64-linux-gnu-gcc"


[profile.test]
debug = 1          # or 0 if you don't even want line numbers
split-debuginfo = "packed"
strip = true
